/*
 * Boot splash: the logo image (optional) plus the firmware name and version.
 */
#include "splash.h"
#include "sdkconfig.h"

#if CONFIG_UNCHAINED_DISPLAY_ENABLED

#include <string.h>

#include "esp_app_desc.h"

#include "display.h"
#include "font.h"
#include "gfx.h"

#if CONFIG_UNCHAINED_DISPLAY_LOGO
#include "logo_img.h"                       /* generated by CMake from utils/logo */
#endif

#define FW_NAME  "Bluetooth Unchained"
#define LINE_GAP 4                           /* px between the name and version lines */
#define C_BG     GFX_SWAP(0x0000)                    /* black */
#define C_NAME   GFX_SWAP(0xFFFF)                    /* white */
#define C_VER    GFX_SWAP(GFX_RGB565(150, 150, 150)) /* dim grey */

static void center_text(int y, const char *s, uint16_t fg)
{
    int x = (display_width() - (int)strlen(s) * font8x8.w) / 2;
    if (x < 0) x = 0;
    display_draw_text(x, y, s, &font8x8, fg, C_BG);
}

bool splash_show(void)
{
    int h = display_height();
    /* ESP-IDF derives this from `git describe` (see the build's PROJECT_VER). */
    const char *version = esp_app_get_description()->version;

    int name_y;
#if CONFIG_UNCHAINED_DISPLAY_LOGO
    display_draw_image(0, 0, LOGO_IMG_W, LOGO_IMG_H, logo_img);   /* full-screen */
    name_y = h / 2 + 40;                                  /* just below the logo band */
#else
    display_fill_rect(0, 0, display_width(), h, C_BG);
    name_y = (h - (2 * font8x8.h + LINE_GAP)) / 2;        /* centre the two-line block */
#endif
    center_text(name_y, FW_NAME, C_NAME);
    center_text(name_y + font8x8.h + LINE_GAP, version, C_VER);
    return true;
}

#else /* !CONFIG_UNCHAINED_DISPLAY_ENABLED */

bool splash_show(void) { return false; }

#endif
