/*
 * Boot splash: the logo image (optional) plus the firmware name.
 */
#include "splash.h"
#include "sdkconfig.h"

#if CONFIG_UNCHAINED_DISPLAY_ENABLED

#include <string.h>

#include "display.h"
#include "font.h"
#include "gfx.h"

#if CONFIG_UNCHAINED_DISPLAY_LOGO
#include "logo_img.h"                       /* generated by CMake from utils/logo */
#endif

#define FW_NAME "Bluetooth Unchained"       /* shown under the logo; a version
                                             * line can be added the same way */
#define C_BG    GFX_SWAP(0x0000)            /* black */
#define C_NAME  GFX_SWAP(0xFFFF)            /* white */

bool splash_show(void)
{
    int w = display_width(), h = display_height();
    int nx = (w - (int)strlen(FW_NAME) * font8x8.w) / 2;
    if (nx < 0) nx = 0;

#if CONFIG_UNCHAINED_DISPLAY_LOGO
    display_draw_image(0, 0, LOGO_IMG_W, LOGO_IMG_H, logo_img);   /* full-screen */
    display_draw_text(nx, h / 2 + 40, FW_NAME, &font8x8, C_NAME, C_BG);
#else
    display_fill_rect(0, 0, w, h, C_BG);
    display_draw_text(nx, (h - font8x8.h) / 2, FW_NAME, &font8x8, C_NAME, C_BG);
#endif
    return true;
}

#else /* !CONFIG_UNCHAINED_DISPLAY_ENABLED */

bool splash_show(void) { return false; }

#endif
